version: '3.3'
services:
    knt-backend:
        container_name: knt-backend
        image: 'knt-backend:latest'
        ports:
            - '5000:5000'
        volumes:
            - './database:/database'
            - './logs:/logs'
