port: ":5000"
database: "./app.db"
cors: "*"


#These routes with their explanations are available within the documentation provided in docs
routes:
  ping: "/ping"
  #Basic routes
  basicEndpoint: "/users"

  getUsers: "/"
  getUser: "/{userId}" 
  makePurchase: "/{userId}/purchase"

  getProducts: "/products"

  #Admin routes
  adminEndpoint: "/admin"

  getUserAdmin: "/users/{userId}"
  createNewUser: "/users/{userId}"
  deleteUser: "/users/{userId}"
  updateUser: "/users/{userId}"
  updateUserMoney: "/users/{userId}/money"
  getUsersAdmin: "/users"

  createNewProduct: "/products"
  deleteProduct: "/products/{productId}"
  updateProduct: "/products/{productId}"




