port: ":5000"
database: "./app.db"


routes: 
  ping: "/ping"
  getUserList: "/users"
  getUser: "/user/validate" #This call must contain an basic auth header of username and password. 
                    #This is not the most secure solution available, but for the purposes of this project it will suffice.
  spendMoney: "/user/spend/{amount}" #same as the previous call 
  getProducts: "/products"
