openapi: '3.0.2'
info:
  title: KnT Backend
  version: '1.0'
servers:
  - url: http://127.0.0.1:5000/
paths:
  /ping:
    get:
      description: "Basic ping function accessable without any keys"
      tags:
        - "Misc"
      responses:
        '200':
          description: OK
  /users:
    get:
      tags:
        - "User Basic"
      security:
        - ApiKeyAuth: []
      description: 'Get information about all registered users accessible with a user api key'
      parameters: []
      responses:
        '200':
          description: A list of user objects with removed sensitive information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
                  
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '407':
          $ref: "#/components/responses/ForbidenError"
  /users/products:
    get:
      tags:
        - "Product Basic"
      description: 'Retrieve a list of products from the database'
      parameters: []
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: A list of product objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/product"
                  
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '407':
          $ref: "#/components/responses/ForbidenError"
  /admin/products:
    put:
      tags:
        - "Product Admin"
      description: 'Edit product'
      security:
        - ApiKeyAuth: []
      parameters: 
        - in: path
          name: productId
          schema:
            type: integer
          required: true
          description: Numeric ID of the product to target
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/fullproduct"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/fullproduct"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '407':
          $ref: "#/components/responses/ForbidenError"
    get:
      tags:
        - "Product Admin"
      description: 'Retrieve full data on all products'
      security:
        - ApiKeyAuth: []

      responses:
        '200':
          description: A list of product objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/fullproduct"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '407':
          $ref: "#/components/responses/ForbidenError"
    post:
      tags:
        - "Product Admin"
      description: 'Create a new product in the database'
      security:
        - ApiKeyAuth: []
      requestBody:
        description: 'Basic product to create'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'

      responses:
        '201':
          description: "Created"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '407':
          $ref: "#/components/responses/ForbidenError"
  /admin/products/{productId}:
    get:
      tags:
        - "Product Admin"
      description: 'Retrieve full data on all products'
      security:
        - ApiKeyAuth: []
      parameters: 
        - in: path
          required: true
          name: userId
          schema:
            type: integer
      responses:
        '200':
          description: A list of product objects
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/fullproduct"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '407':
          $ref: "#/components/responses/ForbidenError"
  /users/{userId}/purchase:
    post:
      tags:
        - "User Basic"
      description: 'Send a list of purchased products'
      security:
        - ApiKeyAuth: []
      parameters: 
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to target
      requestBody:
        description: 'List of products the user has bought'
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: user pin
                  example: "1234"
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: integer
                        description: id of the product
                        example: 1
                      amount:
                        type: integer
                        description: amount of the product
                        example: 1
      responses:
        '201':
          description: "Created"
          content:
            application/json:
              schema:
                type: object
                properties:
                  moneySpent:
                    example: 80
                    type: integer
                    description: Money that has been deducted
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '407':
          $ref: "#/components/responses/ForbidenError"
  /users/{userId}:
    get:
      tags:
        - "User Basic"
      description: 'Get data of a specific user'
      parameters: 
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to target
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '407':
          $ref: "#/components/responses/ForbidenError"
  /admin/users/{userId}:
    get:
      tags:
        - "User Admin"
      security:
        - ApiKeyAuth: []
      description: 'Get complete information about a registered user with a specific id'
      parameters: 
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to target
      responses:
        '200':
          description: A object of full user prividing complete user data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
                  
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '407':
          $ref: "#/components/responses/ForbidenError"
    post:
      tags:
        - "User Admin"
      description: 'Create new user'
      parameters: 
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to target
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/fulluser"
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '407':
          $ref: "#/components/responses/ForbidenError"
    put:
      tags:
        - "User Admin"
      description: 'Edit userdata'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/fulluser"
      parameters: 
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to target
      security:
        - ApiKeyAuth: []
      responses:
        '204':
          description: No content
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '407':
          $ref: "#/components/responses/ForbidenError"
  /admin/users/{userId}/balance:
    post:
      tags:
        - "User Admin"
      description: 'Add balance to a users account'
      security:
        - ApiKeyAuth: []
      parameters: 
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to target
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                balance:
                  example: 80 
                  type: integer
                  description: Amount in cents
      responses:
        '204':
          description: OK
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '407':
          $ref: "#/components/responses/ForbidenError"
  /admin/users:
    get:
      tags:
        - "User Admin"
      description: 'Get complete list of data on all of the users'
      parameters: []
      security: 
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/fulluser"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '407':
          $ref: "#/components/responses/ForbidenError"
components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: integer
          description: The user ID.
          example: 1
        firstName:
          type: string
          description: The users first name.
          example: Person
        lastName:
          type: string
          description: The users last name.
          example: Personson
        balance:
          type: integer
          description: The users balance amount in cents
          example: 8154
    fulluser:
      type: object
      properties:
        id:
          type: integer
          description: The user ID.
          example: 1
        firstName:
          type: string
          description: The users first name.
          example: Person
        lastName:
          type: string
          description: The users last name.
          example: Personson
        vunetId:
          type: string
          description: vunetId
          example: pps999
        password:
          type: string
          description: new password (will be hashed in the Backend) (leave empty if not changed)
          example: "12345678"
        balance:
          type: integer
          description: The users balance amount in cents
          example: 154840
        visibility:
          type: integer
          description: Visibility status of the user 0 will make the user invisable to the knt front end
          example: 1
    product:
      type: object
      properties:
        id:
          type: integer
          description: The products ID.
          example: 1
        price:
          type: integer
          description: The products price in cents
          example: 80
        name:
          type: string
          description: The products name
          example: Beer
    fullproduct:
      type: object
      properties:
        id:
          type: integer
          description: The products ID.
          example: 1
        price:
          type: integer
          description: The products price in cents
          example: 80
        name:
          type: string
          description: The products name
          example: Beer
        visibility:
          type: integer
          description: Visibility status of the product will make the product invisable to the knt front end
          example: 1
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: Api key for the knt (test defined in backend root)

  responses:
    UnauthorizedError:
      description: API key is missing or invalid
    ForbidenError:
      description: Api key does not have the necessary permissions to carry out this request